### ISSUE TITLE
You can use filter or find

### ISSUE THREAD

**Issue by ragnta** [reap2121/SudokuSolver#2]
https://github.com/reap2121/SudokuSolver/blob/548f8efc8a819647eb6eb442598fd4da0faca1fb/src/InputCollector.js#L9

**Comment by reap2121** [comment]
I changed it to find

**Comment by ragnta** [comment]
It's the longest solution for using find. (:
Let's take a look how the find function is working!

you have a sample array. The find method has 2 parameters (callback, and thisarg)
In this case you define the callback as an arrow function. (the callback has 3 parameters 
you defined the callback like this:
function(element){
 if(element.id == id)
        {
            return true;
        }
}
1. when you use only one parameter you can omit its parentheses (like Java 8 Predicates ) 
2. if you define an arrow function with only one return you don't have to use brackets.

ex.: var half = (a) => a/2;
half(4) - '2'

ref: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find 
https://javascript.info/function-expressions-arrows
https://howtodoinjava.com/java8/how-to-use-predicate-in-java-8/

**Comment by reap2121** [comment]
As the ancient Hungarian laborer saying goes: "Jóvanazúgy". But I fixed it anyway :)

**Comment by ragnta** [comment]
It's too long.
you wrote 
if(isTrue){
  return true;
}
else{
  return false;
}
you should return only the condition, too.
